---
title: "Fieldwork Analysis"
author: "ONEILL"
date: "10/11/2019"
output: html_document
---


```{r}
library(tidyverse)
library(lubridate)
library(BIOMASS)
library(ape)
library(ggplot2)
library(measurements)
```

```{r}
Field_Data <- read.csv("Data/Popa_Fieldwork/Popa_Fieldwork(23-10-2019).csv", stringsAsFactors = F)
```

**Checking typos in taxonomy**

```{r}
Taxo <- correctTaxo(genus=Field_Data$Genus, species = Field_Data$Species)
Field_Data$genusCorr <- Taxo$genusCorrected
Field_Data$speciesCorr <- Taxo$speciesCorrected
```
**Retrieving APG III Families and Orders from Genus names**

```{r}
APG <- getTaxonomy(Field_Data$genusCorr, findOrder = T)
Field_Data$familyAPG <- APG$family
Field_Data$orderAPG <- APG$order
```

**RETRIEVE WOOD DENSITY**

```{r}
dataWD <- getWoodDensity(genus=as.character(Field_Data$genusCorr),
                         species=as.character(Field_Data$speciesCorr),
                         stand=Field_Data$Plot)
```


```{r}
sum(dataWD$levelWD == "species")

sum(dataWD$levelWD == "genus")

sum(!dataWD$levelWD%in%c("genus","species"))

Field_Data$WD <- dataWD$meanWD
str(Field_Data)




```

**Computing AGB**

```{r}
AGBtree<-computeAGB(D=Field_Data$DBH_cm,
                    WD=Field_Data$WD,
                    H = Field_Data$Height_m)
# Compute AGB(Mg) per tree----
Field_Data$AGB_Mg <- AGBtree

# Compute Carbon (Mg) per tree --
Field_Data <- Field_Data %>%
  mutate(Carbon_Mg= AGB_Mg*0.47) %>% mutate(C_Tree_Ha = Carbon_Mg/0.04)
str(Field_Data)
Field_Data$Plot <- factor(Field_Data$Plot)

boxplot(C_Tree_Ha~Plot, data=Field_Data)
summary(aov(C_Tree_Ha ~ factor(Plot), data = Field_Data))
 
Field_Carbon <- Field_Data %>%
  group_by(Plot) %>%
  dplyr::summarise(Total_C = sum(C_Tree_Ha)) %>% rename(Plot_Number=Plot)

ggplot(data=Field_Carbon, aes(x=as.numeric(Plot_Number),y =Total_C, color=as.numeric(Plot_Number)))+ geom_point()+ geom_line()+
      labs(title = "Carbon storage in 20 Permanent sample plots", 
       x= "Plot",
       y= "Carbon(t/ha)")+
  theme(axis.text.x = element_text(size=7, angle = 0, vjust = 0.5),
        axis.text.y = element_text(size = 7))
 

```

```{r}
hist(Field_Data$Height_m)
hist(Field_Data$DBH_cm)
ggplot(data = Field_Data, aes(y = Height_m, x = log(DBH_cm))) + 
  geom_point(color='green') +
  geom_smooth(method = "lm", se = FALSE)

```


